//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoContacts.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoContacts.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Developer Advocates.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        internal static string ButtonFollow {
            get {
                return ResourceManager.GetString("ButtonFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Current Location.
        /// </summary>
        internal static string ButtonSyncLocation {
            get {
                return ResourceManager.GetString("ButtonSyncLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Neaby CDAs.
        /// </summary>
        internal static string FindCloseCDAs {
            get {
                return ResourceManager.GetString("FindCloseCDAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hometown.
        /// </summary>
        internal static string Hometown {
            get {
                return ResourceManager.GetString("Hometown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue as Guest.
        /// </summary>
        internal static string LoginPageGuest {
            get {
                return ResourceManager.GetString("LoginPageGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDA Login.
        /// </summary>
        internal static string LoginPageLoginWithMicrosoft {
            get {
                return ResourceManager.GetString("LoginPageLoginWithMicrosoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Microsoft Cloud Developer Advocate contacts application. This app enables you to browse and find CDAs near you..
        /// </summary>
        internal static string LoginPageWelcome {
            get {
                return ResourceManager.GetString("LoginPageWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears that no CDAs are nearby :(.
        /// </summary>
        internal static string NoCDAsNearby {
            get {
                return ResourceManager.GetString("NoCDAsNearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un oh, looks like your device is offline. Check your connection and try again..
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Checked-In.
        /// </summary>
        internal static string RecentCheckin {
            get {
                return ResourceManager.GetString("RecentCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string TitleAllContacts {
            get {
                return ResourceManager.GetString("TitleAllContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby.
        /// </summary>
        internal static string TitleNearby {
            get {
                return ResourceManager.GetString("TitleNearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Current Town.
        /// </summary>
        internal static string TitleUpdateLocation {
            get {
                return ResourceManager.GetString("TitleUpdateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string ToolbarSettings {
            get {
                return ResourceManager.GetString("ToolbarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Location.
        /// </summary>
        internal static string ToolbarUpdateLocation {
            get {
                return ResourceManager.GetString("ToolbarUpdateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing with the cloud....
        /// </summary>
        internal static string UpdateLocationBackend {
            get {
                return ResourceManager.GetString("UpdateLocationBackend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uh oh, looks like we weren&apos;t able to update your location..
        /// </summary>
        internal static string UpdateLocationError {
            get {
                return ResourceManager.GetString("UpdateLocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Being smart and doing some geocoding....
        /// </summary>
        internal static string UpdateLocationGeocoding {
            get {
                return ResourceManager.GetString("UpdateLocationGeocoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When updating your current location the town that you are currently in will be updated for everyone to see and to help find CDAs nearby..
        /// </summary>
        internal static string UpdateLocationMessage {
            get {
                return ResourceManager.GetString("UpdateLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting your location....
        /// </summary>
        internal static string UpdatingLocation {
            get {
                return ResourceManager.GetString("UpdatingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location has been updated and synced!.
        /// </summary>
        internal static string UpdatingLocationUpdated {
            get {
                return ResourceManager.GetString("UpdatingLocationUpdated", resourceCulture);
            }
        }
    }
}
