//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoContacts.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GeoContacts.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string ButtonFollow {
            get {
                return ResourceManager.GetString("ButtonFollow", resourceCulture);
            }
        }
        
        internal static string ButtonMood {
            get {
                return ResourceManager.GetString("ButtonMood", resourceCulture);
            }
        }
        
        internal static string ButtonSync {
            get {
                return ResourceManager.GetString("ButtonSync", resourceCulture);
            }
        }
        
        internal static string ButtonSyncLocation {
            get {
                return ResourceManager.GetString("ButtonSyncLocation", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string ErrorNeedLocation {
            get {
                return ResourceManager.GetString("ErrorNeedLocation", resourceCulture);
            }
        }
        
        internal static string FindCloseCDAs {
            get {
                return ResourceManager.GetString("FindCloseCDAs", resourceCulture);
            }
        }
        
        internal static string Hometown {
            get {
                return ResourceManager.GetString("Hometown", resourceCulture);
            }
        }
        
        internal static string LoginPageGuest {
            get {
                return ResourceManager.GetString("LoginPageGuest", resourceCulture);
            }
        }
        
        internal static string LoginPageLoginWithMicrosoft {
            get {
                return ResourceManager.GetString("LoginPageLoginWithMicrosoft", resourceCulture);
            }
        }
        
        internal static string LoginPageWelcome {
            get {
                return ResourceManager.GetString("LoginPageWelcome", resourceCulture);
            }
        }
        
        internal static string NoCDAsNearby {
            get {
                return ResourceManager.GetString("NoCDAsNearby", resourceCulture);
            }
        }
        
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string RecentCheckin {
            get {
                return ResourceManager.GetString("RecentCheckin", resourceCulture);
            }
        }
        
        internal static string TitleAllContacts {
            get {
                return ResourceManager.GetString("TitleAllContacts", resourceCulture);
            }
        }
        
        internal static string TitleNearby {
            get {
                return ResourceManager.GetString("TitleNearby", resourceCulture);
            }
        }
        
        internal static string TitleUpdateLocation {
            get {
                return ResourceManager.GetString("TitleUpdateLocation", resourceCulture);
            }
        }
        
        internal static string ToolbarSettings {
            get {
                return ResourceManager.GetString("ToolbarSettings", resourceCulture);
            }
        }
        
        internal static string ToolbarUpdateLocation {
            get {
                return ResourceManager.GetString("ToolbarUpdateLocation", resourceCulture);
            }
        }
        
        internal static string UpdateLocationBackend {
            get {
                return ResourceManager.GetString("UpdateLocationBackend", resourceCulture);
            }
        }
        
        internal static string UpdateLocationError {
            get {
                return ResourceManager.GetString("UpdateLocationError", resourceCulture);
            }
        }
        
        internal static string UpdateLocationGeocoding {
            get {
                return ResourceManager.GetString("UpdateLocationGeocoding", resourceCulture);
            }
        }
        
        internal static string UpdateLocationMessage {
            get {
                return ResourceManager.GetString("UpdateLocationMessage", resourceCulture);
            }
        }
        
        internal static string UpdatingLocation {
            get {
                return ResourceManager.GetString("UpdatingLocation", resourceCulture);
            }
        }
        
        internal static string UpdatingLocationUpdated {
            get {
                return ResourceManager.GetString("UpdatingLocationUpdated", resourceCulture);
            }
        }
    }
}
